### ISSUE TITLE
[Feature Request]: Automate Import of Docs from Disparate Repos

### ISSUE THREAD

**Issue by awmatheson** [machine-learning-apps/MLOps#3]
**Is your feature request related to a problem? Please describe.**
To minimize the amount of copy and pasting to import docs from one repo to another and make maintaining the centralized docs easier.

**Describe the solution you'd like**
An action that can automatically pull the readme from a repo or updates from that repo to the `machine-learning-apps/MLOps` repo.

**Comment by marvinbuss** [comment]
- [x] Workspace Action
- [x] Compute Action
- [x] Run Action
- [x] Register Model Action
- [x] Deploy Action

**Comment by marvinbuss** [comment]
Added workflows to all actions. Changes are automatically synched.
